add all contributors to readme
ariefrahmansyah/remembergaza pull request #19
Opened 2024-05-01 14:06 UTC by akhil0203

fixes #17 

add all contributors bot to the the repository.
configure the bot
add @akhil0203 to contributors list using [(to add new contributor)](https://allcontributors.org/docs/en/bot/usage)

2024-05-01 14:12 UTC, akhil0203 commented
hey @ariefrahmansyah  I added the all contributors bot to the repository and all other necessary files to the repo.

For demo case I have added myself(@akhil0203) to the contributors list.

There is necessity to install [all contributors bot Github app](https://allcontributors.org/docs/en/bot/installation) to the original repo which can be authenticated by the owner.

Additional files are added.

2024-05-01 14:43 UTC, ariefrahmansyah requested changes

2024-05-01 14:43 UTC, ariefrahmansyah commented on README.md
> -# Remember Gaza
Why this line got deleted? Can you add this back?

2024-05-02 05:07 UTC, ariefrahmansyah approved these changes
LGTM! Thanks, @akhil0203!

2024-05-02 05:07 UTC, merged